site_name: image_hoarder
site_description: Image storing application for HexOcean recruitment process.
repo_url: https://github.com/sunnyfloyd/hexocean_image_upload
site_dir: site
copyright: Copyright &copy; 2020, <a href="https://github.com/sunnyfloyd">sunnyfloyd</a>.
dev_addr: 0.0.0.0:8001

nav:
  - Home: 'index.md'
  - API:
    - Authentication: 'api/authentication.md'
    - Users: 'api/users.md'
