# Generated by Django 3.2.9 on 2021-11-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='is_original',
            field=models.BooleanField(default=True),
        ),
    ]
