# Generated by Django 3.2.9 on 2021-11-07 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_thumbnail_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnail',
            name='plan',
        ),
    ]
