# Generated by Django 3.2.9 on 2021-11-10 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_image_is_original'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='expiry_after',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(30000)]),
        ),
    ]
