# Generated by Django 3.2.9 on 2021-11-08 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_remove_thumbnail_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='height',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(100)]),
        ),
    ]
