# Generated by Django 3.2.9 on 2021-11-11 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_templink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='expiry_after',
        ),
    ]
