# Generated by Django 3.2.9 on 2021-11-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211109_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='has_expiry_link',
            field=models.BooleanField(default=False),
        ),
    ]
