# Generated by Django 3.2.9 on 2021-11-07 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('users', '0003_auto_20211107_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='thumbnail_options',
            field=models.ManyToManyField(related_name='plans', to='images.Thumbnail'),
        ),
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.plan'),
            preserve_default=False,
        ),
    ]
