# Generated by Django 3.2.9 on 2021-11-07 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20211107_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='plan',
        ),
    ]
