# Generated by Django 3.2.9 on 2021-11-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_thumbnail_plan'),
        ('users', '0007_alter_user_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='thumbnail_options',
            field=models.ManyToManyField(blank=True, null=True, related_name='plans', to='images.Thumbnail'),
        ),
    ]
