# Generated by Django 3.2.9 on 2021-11-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_thumbnail_height'),
        ('users', '0008_alter_plan_thumbnail_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='thumbnail_options',
            field=models.ManyToManyField(blank=True, related_name='plans', to='images.Thumbnail'),
        ),
    ]
